{
 "title": "FIO Benchmark Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "fio_read_lat_pct95{benchmark=\"latency\"}",
     "legendFormat": "Read Latency 95th Percentile benchmark={{ benchmark }}"
    },
    {
     "expr": "fio_write_lat_pct95{benchmark=\"latency\"}",
     "legendFormat": "Write Latency 95th Percentile benchmark={{ benchmark }}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fio_read_iops{benchmark=\"latency\"}",
     "legendFormat": "Read IOPS benchmark={{ benchmark }}"
    },
    {
     "expr": "fio_write_iops{benchmark=\"latency\"}",
     "legendFormat": "Write IOPS benchmark={{ benchmark }}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "fio_read_bandwidth_kbps",
     "legendFormat": "Read Throughput benchmark={{ benchmark }}"
    },
    {
     "expr": "fio_write_bandwidth_kbps",
     "legendFormat": "Write Throughput benchmark={{ benchmark }}"
    }
   ]
  }
 ]
}